# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

- name: auto-pull-request-merge
  # You may pin to the exact commit or the version.
  # uses: KeisukeYamashita/auto-pull-request-merge@f16c055886db96657279e79ce5ba7979738ac1e8
  uses: KeisukeYamashita/auto-pull-request-merge@v1
  with:
    # Check all status before merge
    checkStatus: # optional, default is true
    # Comment before merge
    comment: # optional, default is 
    # Seconds between the check
    intervalSeconds: # optional, default is 0.1
    # Fail the step if the PR is not found or merged
    failStep: # optional, default is true
    # Comma seperated labes that target pull request should have
    labels: # optional, default is 
    # Comma seperated labes that target pull request should not have
    ignoreLabels: # optional, default is 
    # The GitHub repository containing the issue or pr.
    repository: # optional, default is ${{ github.repository }}
    # Number of the pull request
    pullRequestNumber: # optional, default is ${{ github.event.pull_request.number }}
    # SHA of the pull request commit
    sha: # optional, default is ${{ github.event.pull_request.head.sha }}
    # Seconds to timeout
    timeoutSeconds: # optional, default is 60
    # Credential to access to the repo to post the comment
    token: # optional, default is ${{ github.token }}
